Category.create!(
  [
    { id: 1, name: "青年漫画" },
    { id: 2, name: "少年漫画" },
    { id: 3, name: "女性漫画" },
    { id: 4, name: "少女漫画" },
    { id: 5, name: "アクション" },
    { id: 6, name: "アドベンチャー" },
    { id: 7, name: "SF" },
    { id: 8, name: "ホラー" },
    { id: 9, name: "スポーツ" },
    { id: 10, name: "ヒューマンドラマ" },
    { id: 11, name: "医療系" },
    { id: 12, name: "青春" },
    { id: 13, name: "恋愛" },
    { id: 14, name: "ギャグ" },
    { id: 15, name: "職業・ビジネス" },
    { id: 16, name: "歴史系" },
    { id: 17, name: "ミステリー" },
    { id: 18, name: "ファンタジー" },
    { id: 19, name: "ヤンキー" },
    { id: 20, name: "料理" },
    { id: 21, name: "ライトノベル" },
    { id: 22, name: "BL" },
    { id: 23, name: "アダルト" }
  ]
)

User.create!(
  [
    { id: 1,
      username: "名無し人",
      sex: "男",
      email: "sample@example.com",
      password: "password",
      password_confirmation: "password" },
    { id: 2,
      username: "さんぷるユーザー",
      sex: "女",
      email: "sample2@example.com",
      password: "password",
      password_confirmation: "password" }
  ]
)

Post.create!(
  [
    { id: 11, 
      title: "NANAについて語ろう",
      text: "ヤス大好き",
      user_id: 2 },
    { id: 10, 
      title: "「医龍」",
      text: "ドラマも面白かった",
      user_id: 2 },
    { id: 9, 
      title: "魁!!クロマティ高校って",
      text: "メカ沢くん",
      user_id: 1 },
    { id: 8, 
      title: "ふたりエッチ",
      text: "アダルト界の帝王",
      user_id: 1 },
    { id: 7, 
      title: "シャーマンキングについて語ろう",
      text: "懐かしいよね",
      user_id: 2 },
    { id: 6, 
      title: "食戟のソーマ",
      text: "面白い",
      user_id: 1 },
    { id: 5, 
      title: "僕等がいた Part1",
      text: "青春こそ",
      user_id: 2 },
    { id: 4, 
      title: "ハンターハンター芸人",
      text: "天才奇才",
      user_id: 1 },
    { id: 3, 
      title: "キングダム Part1",
      text: "現役最強の漫画",
      user_id: 1 },
    { id: 2, 
      title: "スラムダンク芸人",
      text: "史上最高の漫画",
      user_id: 1 },
    { id: 1, 
      title: "ワンピースについて語ろう",
      text: "大海賊時代",
      user_id: 1 }
  ]
)

CategoryPost.create!(
  [
    { id: 1,
      post_id: 1,
      category_id: 2 },
    { id: 2,
      post_id: 1,
      category_id: 5 },
    { id: 3,
      post_id: 1,
      category_id: 6 },
    { id: 4,
      post_id: 1,
      category_id: 10 },
    { id: 5,
      post_id: 2,
      category_id: 2 },
    { id: 6,
      post_id: 2,
      category_id: 9 },
    { id: 7,
      post_id: 2,
      category_id: 10 },
    { id: 8,
      post_id: 2,
      category_id: 12 },
    { id: 9,
      post_id: 2,
      category_id: 19 },
    { id: 10,
      post_id: 3,
      category_id: 1 },
    { id: 11,
      post_id: 3,
      category_id: 5 },
    { id: 12,
      post_id: 3,
      category_id: 10 },
    { id: 13,
      post_id: 3,
      category_id: 16 },
    { id: 14,
      post_id: 4,
      category_id: 2 },
    { id: 15,
      post_id: 4,
      category_id: 5 },
    { id: 16,
      post_id: 4,
      category_id: 6 },
    { id: 17,
      post_id: 5,
      category_id: 3 },
    { id: 18,
      post_id: 5,
      category_id: 4 },
    { id: 19,
      post_id: 5,
      category_id: 10 },
    { id: 20,
      post_id: 5,
      category_id: 12 },
    { id: 21,
      post_id: 5,
      category_id: 13 },
    { id: 22,
      post_id: 6,
      category_id: 2 },
    { id: 23,
      post_id: 6,
      category_id: 12 },
    { id: 24,
      post_id: 6,
      category_id: 20 },
    { id: 25,
      post_id: 7,
      category_id: 2 },
    { id: 26,
      post_id: 7,
      category_id: 5 },
    { id: 27,
      post_id: 7,
      category_id: 6 },
    { id: 28,
      post_id: 7,
      category_id: 17 },
    { id: 29,
      post_id: 8,
      category_id: 1 },
    { id: 30,
      post_id: 8,
      category_id: 13 },
    { id: 31,
      post_id: 8,
      category_id: 23 },
    { id: 32,
      post_id: 9,
      category_id: 1 },
    { id: 33,
      post_id: 9,
      category_id: 12 },
    { id: 34,
      post_id: 9,
      category_id: 14 },
    { id: 35,
      post_id: 9,
      category_id: 19 },
    { id: 36,
      post_id: 10,
      category_id: 1 },
    { id: 37,
      post_id: 10,
      category_id: 10 },
    { id: 38,
      post_id: 10,
      category_id: 11 },
    { id: 39,
      post_id: 10,
      category_id: 15 },
    { id: 40,
      post_id: 11,
      category_id: 3 },
    { id: 41,
      post_id: 11,
      category_id: 4 },
    { id: 42,
      post_id: 11,
      category_id: 10 },
    { id: 43,
      post_id: 11,
      category_id: 13 }
  ]
)

Response.create!(
  [
    { id: 1, 
      post_id: 1,
      text: "ゴールドロジャー",
      user_id: 1 },
    { id: 2, 
      post_id: 1,
      text: "今熱い",
      user_id: 2 },
    { id: 3, 
      post_id: 1,
      text: "今週の展開が良い",
      user_id: 1 },
    { id: 4, 
      post_id: 2,
      text: "いつ読んでも泣けるよね",
      user_id: 1 },
    { id: 5, 
      post_id: 2,
      text: "どの時代でも色褪せない",
      user_id: 2 },
    { id: 6, 
      post_id: 3,
      text: "李牧",
      user_id: 1 },
    { id: 7, 
      post_id: 3,
      text: "王翦",
      user_id: 2 },
    { id: 8, 
      post_id: 3,
      text: "早く来週",
      user_id: 2 },
    { id: 9, 
      post_id: 3,
      text: "来週の展開",
      user_id: 1 },
    { id: 10, 
      post_id: 3,
      text: "兵糧がどうなる",
      user_id: 1 },
    { id: 11, 
      post_id: 3,
      text: "李牧どうなる",
      user_id: 1 },
    { id: 12, 
      post_id: 3,
      text: "かんき死ぬはず",
      user_id: 1 },
    { id: 13, 
      post_id: 3,
      text: "来週！",
      user_id: 1 },
    { id: 14, 
      post_id: 4,
      text: "ゴン",
      user_id: 1 },
    { id: 15, 
      post_id: 4,
      text: "キルア",
      user_id: 1 },
    { id: 16, 
      post_id: 4,
      text: "クラピカ",
      user_id: 1 },
    { id: 17, 
      post_id: 4,
      text: "レオリオ",
      user_id: 1 },
    { id: 18, 
      post_id: 4,
      text: "クロロ・ルシルフル",
      user_id: 1 },
    { id: 19, 
      post_id: 4,
      text: "フェイタン",
      user_id: 1 },
    { id: 20, 
      post_id: 4,
      text: "ネテロ",
      user_id: 1 }
  ]
)